name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  schedule:
  - cron: "43 13 * * 1"
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r18464"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v1
    with:
      josm-revision: ${{ matrix.josm-revision }}
