name: Java CI

on:
  push:
    branches:
      - master
      - $default-branch
      - $protected-branches
  pull_request:
    branches:
      - master
      - $default-branch
  schedule:
  - cron: "43 13 * * 1"
  workflow_dispatch:

jobs:
  call-workflow:
    strategy:
      matrix:
        josm-revision: ["", "r18464"]
    uses: JOSM/JOSMPluginAction/.github/workflows/ant.yml@v1
    with:
      josm-revision: ${{ matrix.josm-revision }}
      java-version: 17

  createtag:
    if: ${{ github.repository == 'JOSM/MapRoulette' && github.ref_type == 'branch' && github.ref_name == 'master' }}
    needs: call-workflow
    name: Create Tag
    runs-on: ubuntu-latest
    outputs:
      revision: ${{ steps.create_revision.outputs.revision }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set revision env variable
        id: create_revision
        # Count the total commits for this branch
        run: |
          revision="v$(git rev-list --count HEAD)"
          git tag $revision
          git push -u origin $revision
          echo "revision=$revision" >> $GITHUB_OUTPUT

  releasing:
    needs: createtag
    name: Run release actions
    uses: ./.github/workflows/ant-release.yml
    with:
      tag: ${{ needs.createtag.outputs.revision }}
    secrets: inherit
